### ISSUE TITLE
Add python sample projects

### ISSUE THREAD

**Issue by SanjulaGanepola** [Mapepire-IBMi/samples#1]

**Comment by Nandini1071** [comment]
Hi, what python projects you are looking for ?

**Comment by SanjulaGanepola** [comment]
> Hi, what python projects you are looking for ?

Hello @Nandini1071. This particular issue was to track creating a sample python project that showcases the mapepire python client for Tech Preview 1. Feel free to contribute other sample projects!

Closing for now as first sample added in https://github.com/Mapepire-IBMi/samples/pull/12
